server:
  port: 8000
spring:
  application:
    name: edge-service
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: auth
              uri: ${auth-service.url:http://localhost:8082}
              predicates:
                - Path=/api/auth/**,/api/users/**,/api/tokens/**
            - id: oauth2-login
              uri: ${auth-service.url:http://localhost:8082}
              predicates:
                - Path=/oauth2/**,/login/oauth2/**
            - id: board
              uri: ${border-service.url:http://localhost:8081}
              predicates:
                - Path=/api/**
          trusted-proxies: ${trusted-proxies:"127\\.0\\.0\\.1|0:0:0:0:0:0:0:1|::1"}