# 실제 값은 env로 주입
spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 639245ff2c1385d59fb018f041ccb78e
            client-secret: iFBj3y8cF5uoVzPC4A3Ju9BHjxcDZcpv